server:
  port: 83
spring:
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
  application:
    name: cloud-consumer-order
service-url:
  nacos-service: http://cloud-nacos-server
server-url: http://cloud-nacos-server
