server:
  port: 80
spring:
  application:
    name: cloud-cousumer-feign
eureka:
  client:
    #是否将自己注册进eurekaServer 默认为ture
    register-with-eureka: true
    #是否从rureka 已有注册信息
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:7001/eureka/,http://localhost:7002/eureka/,http://localhost:7003/eureka/
ribbon:
  ReadTimeout: 5000
  ConnectTimeout: 5000
logging:
  level:
    com.atguigu.springcloud.controller.service.PayFeignServer: debug
