server:
  port: 8005
spring:
  application:
    name: cloud-provide-hystrix
eureka:
  client:
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7002.com:7002/eureka/,http://eureka7003.com:7003/eureka/
    fetch-registry: true
    register-with-eureka: true
  instance:
    instance-id: payment8005